config/routes.rb
Rails.application.routes.draw do
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
	root to: "calendar#calendrier", :lieu => "tous les lieux"
	get 'log_in' => 'user_sessions#new', :as => :log_in
	post 'log_out' => 'user_sessions#destroy', :as => :log_out

  resources :reset_passwords, only: [:new, :create, :update, :edit]
	resource :calendar, only: [:calendrier, :aide], controller: :calendar
	resource :iframe, only: [:calendrier_iframe], controller: :iframe
	resource :specific_iframe, only: [:specific_calendrier_iframe], controller: :specific_iframe
	resources :ics
	resources :seances
	resources :villages
	resources :films
	resources :classifications
	resources :users
	resources :user_sessions, only: [:new, :create, :destroy]
	resources :disponibilites
	get 'specific_calendrier_iframe' => 'specific_iframe#specific_calendrier_iframe'
	get 'calendrier_iframe' => 'iframe#calendrier_iframe'
	get 'aide' => 'calendar#aide'
	get 'calendrier' => 'calendar#calendrier'
	get 'a_completer' => 'seances#a_completer'
	get 'mes_seances' => 'seances#mes_seances'
	get 'toutes_mes_seances' => 'seances#toutes_mes_seances'
	get 'seances_passees' => 'seances#seances_passees'
	get 'edition_calendrier' => 'seances#edition_calendrier'
	get 'entrees' => 'seances#entrees'
	get 'export_csv' => 'seances#export_csv'
	get 'export_nodon_csv' => 'seances#export_nodon_csv'
	get 'export_cc_csv' => 'seances#export_cc_csv'
	get 'export_tournee_csv' => 'seances#export_tournee_csv'
	get 'export_ics' => 'ics#export_ics'
	get 'export_cc_ics' => 'ics#export_cc_ics'
	get 'export_nodon_ics' => 'ics#export_nodon_ics'
	get 'export_tournee_ics' => 'ics#export_tournee_ics'
	get 'ecranvillage' => 'films#ecranvillage'
	get 'films_a_venir' => 'films#films_a_venir'
	get 'tous_les_films' => 'films#tous_les_films'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/seance.rb
class Seance < ApplicationRecord

	belongs_to :film, :inverse_of => :seances, optional: true
	belongs_to :village, :inverse_of => :seances, optional: true
	validates :film_id, :presence => true
	validates :village_id, :presence => true
	validates :horaire, :presence => true
	validates :import_id, :uniqueness => true

	before_create :setup_default_value_for_new_seances
	#throw(:abort)
	before_update :setup_default_value_for_updated_seances
	#throw(:abort)


	def self.lieuxtest
		lieuxtest = Hash[
		"lamastre" => Seance.order(horaire: :asc).map{ |seance|
		 seance if seance.village.commune.upcase == "LAMASTRE" },
		"vernoux"  => Seance.all.order(horaire: :asc).map{ |seance| seance if seance.village.commune.upcase == "VERNOUX" },
		"chalencon" => Seance.all.order(horaire: :asc).map{ |seance| seance if seance.village.commune.upcase == "CHALENCON" },
		"itinerance" => Seance.all.order(horaire: :asc).map{ |seance| seance if seance.village.commune.upcase != "LAMASTRE" &&
		        seance.village.commune.upcase != "VERNOUX" && seance.village.commune.upcase != "CHALENCON" },
		  "tous les lieux" => Seance.all.order(horaire: :asc).map{|seance| seance }
		]
	end

	def self.seances_calendrier
		seances_calendrier = Seance.where({horaire: ((Date.today - 6.day)..(Date.today + 6.day))})
	end

	def self.seances_a_venir
        seances_a_venir = Seance.where({horaire: (Date.today.midnight..Date.today + 60)})
	end

	def self.seances_hier
		seances_hier = Seance.where({horaire: (2.day.ago..Date.today)})
	end

	def self.seances_passees_3_semaines
		seances_passees_3_semaines = Seance.where({horaire: (3.week.ago..(Date.today + 1))}).order(horaire: :asc)
	end

	def self.seances_passees_1_mois
         seances_passees_1_mois = Seance.where({horaire: (30.days.ago..Date.today)}).order(horaire: :desc)
	end

	def self.seances_semaine
         seances_semaine = Seance.where({horaire: (Date.today.midnight..(Date.today + 7))}).order(horaire: :desc)
	end

	def self.seances_1_mois_avant_apres
	    seances_1_mois_avant_apres = Seance.where({horaire: (1.month.ago..(Date.today + 60))}).order(horaire: :asc)
	end

	def self.seances_1_semaine_avant_2_mois_apres
	    seances_1_semaine_avant_1_mois_apres = Seance.where({horaire: (1.week.ago..(Date.today + 60))})
	end

	def self.seances_asc
		seances_asc = Seance.order(horaire: :asc)
	end

	def	self.seances_desc
		seances_desc = Seance.order(horaire: :desc)
	end

	def self.seances_a_completer_projection
		seances_a_completer_projection = Seance.where(projection: [nil, ""]).order(horaire: :asc)
	end

	def self.seances_a_completer_caisse
		seances_a_completer_caisse = Seance.where(caisse: [nil, ""]).order(horaire: :asc)
	end

	def self.seances_date_range
	   	seances_date_range = Seance.where({horaire: (range.to_i.days.ago..Date.today)})
	end

	def self.seances_annulee
	   	seances_annulee = Seance.where({annulee: ["Annulée", nil]})
	end

	def self.to_csv
    attributes = %w{ Subject Start\ Date Start\ Time End\ Date End\ Time Location }

    CSV.generate(headers: true) do |csv|
      csv << attributes

      Seance.seances_1_mois_avant_apres.each do |seance|
        csv << ["#{seance.film.titrefilm} #{seance.version}",seance.horaire.strftime('%d/%m/%Y'),seance.horaire.strftime('%I:%M %p'),seance.horaire.strftime('%d/%m/%Y'),(seance.horaire + 2.hours).strftime('%I:%M %p'),"#{seance.village.commune}, #{seance.village.salle}"]
      end
    end
  end

	def self.search(search)
	  if search
	    film_range = Film.find_by(titrefilm: search)
	    	if film_range
	    		self.where(film_id: film_range)
	    	else
	    		@films = Film.all.order(import_id: :desc)
	  		end
		end
	end

	private

	def setup_default_value_for_new_seances
	  	if self.billets_adultes.blank?
	      self.billets_adultes = 0
     	end
	  	if self.billets_enfants.blank?
	      self.billets_enfants = 0
	  	end
	  	if self.billets_scolaires.blank?
	      self.billets_scolaires = 0
	  	end
	  	if self.total_billets.blank?
	      self.total_billets = 0
	  	end
	  	seance_import_last = Seance.order(:import_id).last
	  	if self.import_id.blank?
	  		self.import_id = seance_import_last.import_id + 1
	  	end
	end

	def setup_default_value_for_updated_seances
	   	self.total_billets = self.billets_adultes + self.billets_enfants + self.billets_scolaires
	end
end

app/controllers/seances_controller.rb
class SeancesController < ApplicationController

  before_action :get_lieu
  before_action :require_login
  before_action :set_seance, only: [:show, :edit, :update, :destroy]

   def index
    @seances = Seance.all
    @disponibilites = Disponibilite.all
    respond_to do |format|
        format.pdf do
        render :pdf => "index.pdf",
          :orientation => 'Landscape',
          :layout => "layouts/pdf",
          :disable_javascript => false,
          show_as_html: params[:debug].present?
        end
      format.html
      end
  end

  def seances_passees
    @seances =  Seance.all.order('horaire DESC').paginate(:page => params[:page])
    respond_to do |format|
        format.pdf do
        render :pdf => "seances_passees.pdf",
          :orientation => 'Landscape',
          :layout => "layouts/pdf",
          :disable_javascript => false,
          show_as_html: params[:debug].present?
        end
      format.html
      end
  end

  def mes_seances
    @seances = Seance.seances_a_venir
    @users = User.all
    user = current_user
  end

  def toutes_mes_seances
    @seances = Seance.all
    @users = User.all
    user = current_user
  end

  def a_completer
    @seances = Seance.all
    @disponibilites = Disponibilite.all
  end

  def edition_calendrier
    @seances = Seance.all
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
      respond_to do |format|
      format.pdf do
        render :pdf => "edition_calendrier.pdf",
          :orientation => 'Landscape',
          :layout => "layouts/pdf",
          :disable_javascript => false,
          show_as_html: params[:debug].present?
        end
      format.html
      end
  end

  def entrees
    @search = SeanceSearch.new(params[:search])
    @seances = @search.scope
    @stats = EntreeFacade.new(@seances)
    @films = Film.all
    respond_to do |format|
        format.pdf do
        render :pdf => "entrees.pdf",
          :layout => "layouts/pdf",
          :disable_javascript => false,
          show_as_html: params[:debug].present?
        end
      format.html
      end
  end

  def export_csv
    @seances = Seance.seances_1_mois_avant_apres
    @films = Film.all
    respond_to do |format|
      format.html
      format.csv { send_data @seances.to_csv, filename: "seances-#{Date.today}.csv" }
    end
  end

  def export_nodon_csv
    @seances = Seance.seances_1_mois_avant_apres
    @films = Film.all
    respond_to do |format|
      format.html
      format.csv { send_data @seances.where(:village_id => 4).to_csv, filename: "seances-nodon-#{Date.today}.csv" }
    end
  end

  def export_cc_csv
    @seances = Seance.seances_1_mois_avant_apres
    @films = Film.all
    respond_to do |format|
      format.html
      format.csv { send_data @seances.where(:village_id => 8).to_csv, filename: "seances-#{Date.today}.csv" }
    end
  end

  def export_tournee_csv
    @seances = Seance.seances_1_mois_avant_apres
    @films = Film.all
    respond_to do |format|
      format.html
      format.csv { send_data @seances.where.not(:village_id => 4).to_csv, filename: "seances-tournee-#{Date.today}.csv" }
    end
  end

  # GET /seances/1
  # GET /seances/1.json
  def show
  end

  # GET /seances/new
  def new
    @seance = Seance.new(params[:seance])
    @films = Film.all
    @villages = Village.all
  end

  # GET /seances/1/edit
  def edit
    @seances = Seance.all
    @villages = Village.all
  end

  # POST /seances
  # POST /seances.json
  def create
    film_selectionne = Film.find_by_id(params["seance"]["film_id"])
    village_selectionne = Village.find_by_id(params["seance"]["village_id"])
    seance = Seance.new(seance_params)
    seance.film_id = film_selectionne.id
    seance.village_id = village_selectionne.id
    seance.save
    redirect_to films_a_venir_url, notice: 'la Séance a bien été créée.'
  end


  # PATCH/PUT /seances/1
  # PATCH/PUT /seances/1.json
  def update
    respond_to do |format|
      if @seance.update(seance_params)
        format.html { redirect_to seance_path, notice: 'La séance a bien été modifiée.' }
      else
        format.html { render :edit }
        format.json { render json: @seance.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /seances/1
  # DELETE /seances/1.json
  def destroy
    @seance.destroy
    respond_to do |format|
      format.html { redirect_to films_a_venir_url, notice: 'La Séance a bien été suprimée.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_seance
      @seance = Seance.find(params[:id])
    end

    def get_lieu
      @lieu = params[:lieu]
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def seance_params
      params.require(:seance).permit(:horaire, :film_id, :village_id, :import_id, :version, :projection, :commentaire, :caisse, :extras, :annulee, :billets_adultes, :billets_scolaires, :billets_enfants, :total_billets, :audio_description )
    end
end

app/helpers/seances_helper.rb
module SeancesHelper
end

app/views/seances/edit.html.erb
<center>
<h1><strong>Éditer une Séance</strong></h1>
<div class="container">
	<%= render 'form' %>
	<div class="actions">
	    <div class="btn-group">
	    <button type="button" class="btn btn-danger">Choix de retour</button>
	        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
	        <span class="caret"></span>
	        <span class="sr-only">Toggle Dropdown</span>
	        </button>
	        <ul class="dropdown-menu" role="menu">
	          <% if @seance.village.commune.downcase == "vernoux" || @seance.village.commune.downcase == "lamastre" || @seance.village.commune.downcase == "chalencon"%>
	            pour <strong><%= @seance.village.commune.upcase %></strong>
	            <li><%= link_to 'Séances', seances_path(:lieu => @seance.village.commune.downcase), :class => "btn btn-success active" %></li>
	            <li><%= link_to 'Séances à compléter', a_completer_path(:lieu => @seance.village.commune.downcase), :class => "btn btn-warning active" %></li>
	            <li><%= link_to 'Séances passées', seances_passees_path(:lieu => @seance.village.commune.downcase), :class => "btn btn-warning active" %></li>
	            <li class="divider"></li>
	          <% else %>
	            <li></li>
	         <% end %>
	            pour <strong>Tous les lieux</strong>
	            <li><%= link_to 'Séances', seances_path(:lieu => "tous les lieux"), :class => "btn btn-success active" %></li>
	            <li><%= link_to 'Séances à compléter', a_completer_path(:lieu => "tous les lieux"), :class => "btn btn-warning active" %></li>
	            <li><%= link_to 'Séances passées', seances_passees_path(:lieu => "tous les lieux"), :class => "btn btn-warning active" %></li>
	            <li class="divider"></li>
	            <li><%= link_to 'Mes Séances', mes_seances_path, :class => "btn btn-primary active" %></li>
	            <li><%= link_to 'Films à venir', films_a_venir_path, :class => "btn btn-success active" %></li>
	            <li class="divider"></li>
	        </ul>
	    </div>
  	</div>
</div>
</center>
<br>

app/views/seances/export_cc_csv.html.erb
<p>Vous pouvez téléchargez le fichier en cliquant sur ce bouton: <%= link_to 'Import séances CC csv', export_cc_csv_path(format: "csv"), :class => "btn btn-warning active" %></p>
<p>Enregistrez le fichier sur votre ordinateur que vous pourrez ensuite ajouter à votre calendrier <strong>Google Agenda</strong> en allant sur sur votre interface Agenda de Google (<strong>avec un  autre navigateur que Google Chrome</strong>, ça ne marche que avec <strong>Firefox</strong> ou <strong>Internet Explorer</strong>, ou autres navigateurs à tester...)</p>
<p>puis dans <strong>'Menu Paramètres'</strong> (une roue dentée en haut à droite), choisir <strong>Paramètres</strong>, sur la colonne de droite choisir <strong>Importer et exporter</strong>, cliquez sur <strong>Séléctionnez un fichier sur votre ordinateur</strong>, sélectionner le fichier que vous venez de télécharger qui doit ressembler à seances-cc-jj_mm_yyyy.csv (jj=jour, mm=mois, yyyy=année), en dessous choisissez à quel agenda vous ajoutez ces dates, puis cliquez sur <strong>Importer</strong>. That's all ! 🙃</p>
<br>

<h3>Et Pour un calendrier <strong>Nextcloud</strong> ?</h3>
<p>un format différent, en .ics qui ressemblerait à celui ci-dessous et qu'il suffit <strong>copier-coller dans un éditeur de texte</strong>, puis de l'enregistrer en ajoutant à la fin du nom du fichier un <strong>.ics</strong> ( par exemple export-seances-cc.ics). Ensuite, on pourra l'importer dans un calendrier Nextcloud.</p>
<p>À noter que ce format est aussi compatible pour les agendas Google</p>
<p>Pour que ce soit plus facile à copier, rendez-vous sur cette page qui s'ouvrira dans un onglet <%= link_to "Page à copier-coller", export_cc_ics_path, :target => "_blank" %></p>
<p>vous pourrez ainsi utiliser avec votre clavier avec :
<ul>
<li> <strong>Ctl+A</strong> pour selectionner tout le texte,</li>
 <li>suivi de <strong>CTL+C</strong> pour tout copier</li>
 <li>puis <strong>Ctl+v</strong> pour coller dans un éditeur de texte (par exemple Notepad++ téléchargeable à cette adresse: <%= link_to "Téléchargement Notepad++", "https://notepad-plus-plus.org/downloads/", :target => "_blank" %>)</li>
</ul>
<br>

BEGIN:VCALENDAR<br>
VERSION:2.0<br>
CALSCALE:GREGORIAN<br>
PRODID:-//SabreDAV//SabreDAV//EN<br>
X-WR-CALNAME:ExportSeancesCentreCulturel-<%= Date.today %><br>
BEGIN:VTIMEZONE<br>
TZID:Europe/Paris<br>
BEGIN:DAYLIGHT<br>
TZOFFSETFROM:+0100<br>
TZOFFSETTO:+0200<br>
TZNAME:CEST<br>
DTSTART:19700329T020000<br>
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3<br>
END:DAYLIGHT<br>
BEGIN:STANDARD<br>
TZOFFSETFROM:+0200<br>
TZOFFSETTO:+0100<br>
TZNAME:CET<br>
DTSTART:19701025T030000<br>
END:STANDARD<br>
END:VTIMEZONE<br>
<% @seances.where(:village_id => 8).each do |se| %>
BEGIN:VEVENT<br>
CREATED:<%= se.created_at.strftime('%Y%m%d') %>T<%= se.created_at.strftime('%H%M%S') %><br>
LAST-MODIFIED:<%= se.updated_at.strftime('%Y%m%d') %>T<%= se.updated_at.strftime('%H%M%S') %><br>
UID:<%= se.id %><br>
SUMMARY:<%= se.film.titrefilm %> <%= se.version %><br>
DTSTART;TZID=Europe/Paris:<%= se.horaire.strftime('%Y%m%d') %>T<%= se.horaire.strftime('%H%M%S') %><br>
DTEND;TZID=Europe/Paris:<%= (se.horaire + 2.hours).strftime('%Y%m%d') %>T<%= (se.horaire + 2.hours).strftime('%H%M%S') %><br>
TRANSP:OPAQUE<br>
LOCATION:<%= se.village.commune %>, <%= se.village.salle %><br>
END:VEVENT<br>
<% end %>
END:VCALENDAR

app/views/seances/export_csv.html.erb
<p>Vous pouvez téléchargez le fichier en cliquant sur ce bouton: <%= link_to 'Import séances csv', export_csv_path(format: "csv"), :class => "btn btn-warning active" %></p>
<p>Enregistrez le fichier sur votre ordinateur que vous pourrez ensuite ajouter à votre calendrier <strong>Google Agenda</strong> en allant sur sur votre interface Agenda de Google (<strong>avec un  autre navigateur que Google Chrome</strong>, ça ne marche que avec <strong>Firefox</strong> ou <strong>Internet Explorer</strong>, ou autres navigateurs à tester...)</p>
<p>🎅 🎁 Et en prime, vous pouvez avoir le fichier que pour la <strong>salle Louis Nodon</strong> ici : <%= link_to 'Import Séances Louis Nodon Google Agenda', export_nodon_csv_path, :class => "btn btn-link active" %> </p>
<p>pour le <strong>Centre Culturel de Lamastre</strong> ici : <%= link_to 'Import Séances Centre Culturel Google Agenda', export_cc_csv_path, :class => "btn btn-link active" %></p> <p>pour la <strong>Tournée (tous les lieux sauf la salle Louis Nodon)</strong> ici : <%= link_to 'Import Séances Tournée Google Agenda', export_tournee_csv_path, :class => "btn btn-link active" %> </p>
<p>puis dans <strong>'Menu Paramètres'</strong> (une roue dentée en haut à droite), choisir <strong>Paramètres</strong>, sur la colonne de droite choisir <strong>Importer et exporter</strong>, cliquez sur <strong>Séléctionnez un fichier sur votre ordinateur</strong>, sélectionner le fichier que vous venez de télécharger qui doit ressembler à seances-jj_mm_yyyy.csv (jj=jour, mm=mois, yyyy=année), en dessous choisissez à quel agenda vous ajoutez ces dates, puis cliquez sur <strong>Importer</strong>. That's all ! 🙃</p>
<p>J'ai fait des tests, si on rajoute des dates qui étaient déjà entrées, elles ne sont pas doublées. Par défaut, j'ai choisi de mettre à toutes les séances une durée de 2 heures.</p>
<br>

<h3>Et Pour un calendrier <strong>Nextcloud</strong> ?</h3>
<p>un format différent, en .ics qui ressemblerait à celui ci-dessous et qu'il suffit <strong>copier-coller dans un éditeur de texte</strong>, puis de l'enregistrer en ajoutant à la fin du nom du fichier un <strong>.ics</strong> ( par exemple export-seances.ics). Ensuite, on peut l'importer dans un calendrier Nextcloud.</p>
<p>(À noter que ce format est aussi compatible pour les agendas Google)</p>
<p>Pour que ce soit plus facile à copier, rendez-vous sur cette page qui s'ouvrira dans un onglet <%= link_to "Page à copier-coller", export_ics_path, :target => "_blank" %></p>
<p>vous pourrez ainsi utiliser avec votre clavier avec :
<ul>
<li> <strong>Ctl+A</strong> pour selectionner tout le texte,</li>
 <li>suivi de <strong>CTL+C</strong> pour tout copier</li>
 <li>puis <strong>Ctl+v</strong> pour coller dans un éditeur de texte (par exemple Notepad++ téléchargeable à cette adresse: <%= link_to "Téléchargement Notepad++", "https://notepad-plus-plus.org/downloads/", :target => "_blank" %>)</li>
</ul>
 <br>

BEGIN:VCALENDAR<br>
VERSION:2.0<br>
CALSCALE:GREGORIAN<br>
PRODID:-//SabreDAV//SabreDAV//EN<br>
X-WR-CALNAME:ExportSeances-<%= Date.today %><br>
X-PUBLISHED-TTL:PT4H<br>
BEGIN:VTIMEZONE<br>
TZID:Europe/Paris<br>
BEGIN:DAYLIGHT<br>
TZOFFSETFROM:+0100<br>
TZOFFSETTO:+0200<br>
TZNAME:CEST<br>
DTSTART:19700329T020000<br>
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3<br>
END:DAYLIGHT<br>
BEGIN:STANDARD<br>
TZOFFSETFROM:+0200<br>
TZOFFSETTO:+0100<br>
TZNAME:CET<br>
DTSTART:19701025T030000<br>
END:STANDARD<br>
END:VTIMEZONE<br>
<% @seances.each do |se| %>
BEGIN:VEVENT<br>
CREATED:<%= se.created_at.strftime('%Y%m%d') %>T<%= se.created_at.strftime('%H%M%S') %><br>
LAST-MODIFIED:<%= se.updated_at.strftime('%Y%m%d') %>T<%= se.updated_at.strftime('%H%M%S') %><br>
UID:<%= se.id %><br>
SUMMARY:<%= se.film.titrefilm %> <%= se.version %><br>
DTSTART;TZID=Europe/Paris:<%= se.horaire.strftime('%Y%m%d') %>T<%= se.horaire.strftime('%H%M%S') %><br>
DTEND;TZID=Europe/Paris:<%= (se.horaire + 2.hours).strftime('%Y%m%d') %>T<%= (se.horaire + 2.hours).strftime('%H%M%S') %><br>
TRANSP:OPAQUE<br>
LOCATION:<%= se.village.commune %>, <%= se.village.salle %><br>
END:VEVENT<br>
<% end %>
END:VCALENDAR

app/views/seances/show.html.erb
<div class="container">
  <center>
    <h1><span class="glyphicon glyphicon-film"></span> <strong>Film : </strong><%=raw @seance.film.titrefilm %> <%= @seance.version %> <%= @seance.audio_description %></h1>
    <h3><strong><span class="glyphicon glyphicon-time"></span> Date : </strong><%= l @seance.horaire, format: :very_long %></h3>
    <h2><span class="glyphicon glyphicon-home"></span> <strong>Lieu : </strong><%= @seance.village.commune.upcase %></h2>
    <% if @seance.version != "" %>
    <h2><span class="glyphicon glyphicon-info-sign"></span> <%= @seance.version %></h2>
    <% end %>
    <% if @seance.audio_description != "" %>
    <h2><i class="fa fa-audio-description"></i> <%= @seance.audio_description %> <i class="fa fa-low-vision"></i></h2>
    <% end %>
    <% if @seance.extras != "" %>
    <h2><span class="glyphicon glyphicon-info-sign"></span> </strong><%= @seance.extras %></h2>
    <% end %>
    <% if @seance.annulee != "" %>
    <h2><span class="glyphicon glyphicon-warning-sign"></span> </strong><%= @seance.annulee %></h2>
    <% end %>
    <% if @seance.projection.present? %>
    <h3><strong><span class="glyphicon glyphicon-facetime-video"></span> Projection : </strong><%= @seance.projection.capitalize %></h3>
    <% end %>
    <% if @seance.caisse.present? %>
    <h3><strong><span class="glyphicon glyphicon-briefcase"></span> Caisse : </strong><%= @seance.caisse.capitalize %></h3>
    <% end %>
    <h3><strong>Commentaire : </strong></h3>
    <p><%=simple_format h @seance.commentaire %></p>
    <h3>Entrées</h3>
    <h4>Billets Adultes: <%= @seance.billets_adultes %>, Billets Enfants:<%= @seance.billets_enfants %>, Billets Scolaires: <%= @seance.billets_scolaires %> </h4>
    <div class="actions">
      <%= link_to 'Modifier ?', edit_seance_path(@seance), :class => "btn btn-warning active" %>
    </div>
  <div class="container">
   <div class="btn-group">
    <button type="button" class="btn btn-danger">Choix de retour</button>
        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <% if @seance.village.commune.downcase == "vernoux" || @seance.village.commune.downcase == "lamastre" || @seance.village.commune.downcase == "chalencon"%>
            pour <strong><%= @seance.village.commune.upcase %></strong>
            <li><%= link_to 'Séances', seances_path(:lieu => @seance.village.commune.downcase), :class => "btn btn-success active" %></li>
            <li><%= link_to 'Séances à compléter', a_completer_path(:lieu => @seance.village.commune.downcase), :class => "btn btn-warning active" %></li>
            <li><%= link_to 'Séances passées', seances_passees_path(:lieu => @seance.village.commune.downcase), :class => "btn btn-warning active" %></li>
            <li class="divider"></li>
          <% else %>
            <li></li>
         <% end %>
            pour <strong>Tous les lieux</strong>
            <li><%= link_to 'Séances', seances_path(:lieu => "tous les lieux"), :class => "btn btn-success active" %></li>
            <li><%= link_to 'Séances à compléter', a_completer_path(:lieu => "tous les lieux"), :class => "btn btn-warning active" %></li>
            <li><%= link_to 'Séances passées', seances_passees_path(:lieu => "tous les lieux"), :class => "btn btn-warning active" %></li>
            <li class="divider"></li>
            <li><%= link_to 'Mes Séances', mes_seances_path, :class => "btn btn-primary active" %></li>
            <li><%= link_to 'Films à venir', films_a_venir_path, :class => "btn btn-success active" %></li>
            <li class="divider"></li>
        </ul>
    </div>
  </div>
  </center>
</div>