config/routes.rb
Rails.application.routes.draw do
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
	root to: "calendar#calendrier", :lieu => "tous les lieux"
	get 'log_in' => 'user_sessions#new', :as => :log_in
	post 'log_out' => 'user_sessions#destroy', :as => :log_out

  resources :reset_passwords, only: [:new, :create, :update, :edit]
	resource :calendar, only: [:calendrier, :aide], controller: :calendar
	resource :iframe, only: [:calendrier_iframe], controller: :iframe
	resource :specific_iframe, only: [:specific_calendrier_iframe], controller: :specific_iframe
	resources :ics
	resources :seances
	resources :villages
	resources :films
	resources :classifications
	resources :users
	resources :user_sessions, only: [:new, :create, :destroy]
	resources :disponibilites
	get 'specific_calendrier_iframe' => 'specific_iframe#specific_calendrier_iframe'
	get 'calendrier_iframe' => 'iframe#calendrier_iframe'
	get 'aide' => 'calendar#aide'
	get 'calendrier' => 'calendar#calendrier'
	get 'a_completer' => 'seances#a_completer'
	get 'mes_seances' => 'seances#mes_seances'
	get 'toutes_mes_seances' => 'seances#toutes_mes_seances'
	get 'seances_passees' => 'seances#seances_passees'
	get 'edition_calendrier' => 'seances#edition_calendrier'
	get 'entrees' => 'seances#entrees'
	get 'export_csv' => 'seances#export_csv'
	get 'export_nodon_csv' => 'seances#export_nodon_csv'
	get 'export_cc_csv' => 'seances#export_cc_csv'
	get 'export_tournee_csv' => 'seances#export_tournee_csv'
	get 'export_ics' => 'ics#export_ics'
	get 'export_cc_ics' => 'ics#export_cc_ics'
	get 'export_nodon_ics' => 'ics#export_nodon_ics'
	get 'export_tournee_ics' => 'ics#export_tournee_ics'
	get 'ecranvillage' => 'films#ecranvillage'
	get 'films_a_venir' => 'films#films_a_venir'
	get 'tous_les_films' => 'films#tous_les_films'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/village.rb
class Village < ApplicationRecord
	has_many :seances, :dependent => :destroy, :inverse_of => :village
	accepts_nested_attributes_for :seances, :allow_destroy => true
	has_many :films, :through => :seances
	validates :id, :uniqueness => true
  validates :commune, :presence => true
	validates :salle, :presence => true
  validates :import_id, :uniqueness => true

  before_create :setup_default_value_for_new_villages
  #throw(:abort)

  private

  def setup_default_value_for_new_villages
      village_import_last = Village.order(:import_id).last
      if self.import_id.blank?
        self.import_id = village_import_last.import_id + 1
      end
  end

end

app/controllers/villages_controller.rb
  class VillagesController < ApplicationController

  skip_before_action :require_login, only: [:index, :show ]
  before_action :set_village, only: [:show, :edit, :update, :destroy]

  # GET /villages
  # GET /villages.json
  def index
    @villages = Village.all
  end

  # GET /villages/1
  # GET /villages/1.json
  def show
  end

  # GET /villages/new
  def new
    @village = Village.new
  end

  # GET /villages/1/edit
  def edit
  end

  # POST /villages
  # POST /villages.json
  def create
    @village = Village.new(village_params)

    respond_to do |format|
      if @village.save
        format.html { redirect_to @village, notice: 'Le lieu a bien été créé.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /villages/1
  # PATCH/PUT /villages/1.json
  def update
    respond_to do |format|
      if @village.update(village_params)
        format.html { redirect_to @village, notice: 'La modification est bien prise en compte.' }
        format.json { render :show, status: :ok, location: @village }
      else
        format.html { render :edit }
        format.json { render json: @village.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /villages/1
  # DELETE /villages/1.json
  def destroy
    @village.destroy
    respond_to do |format|
      format.html { redirect_to villages_url, notice: 'Le lieu a bien été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_village
      @village = Village.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def village_params
      params.require(:village).permit(:import_id ,:commune, :salle)
    end
end

app/helpers/villages_helper.rb
module VillagesHelper
end

app/views/villages/_form.html.erb
<%= form_for(@village) do |f| %>
  <% if @village.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(village.errors.count, "error") %> prohibited this village from being saved:</h2>

      <ul>
      <% village.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :commune %>:
    <%= f.text_field :commune %>
  </div>

  <div class="field">
    <%= f.label :salle %>:
    <%= f.text_field :salle %>
  </div>

  <div class="actions">
    <input type="submit" class="btn btn-warning" value="Valider" />
  </div>
<% end %>

app/views/villages/edit.html.erb
<center>
<h1>Edition du Lieu</h1>
<%= render 'form', village: @village %>

<%= link_to 'Voir', @village, :class => "btn btn-success" %> |
<%= link_to 'Retour liste lieux', villages_path, :class => "btn btn-primary"%>
</center>

app/views/villages/index.html.erb
<center><h1>Lieux</h1></center>
<% if can? :update, Seance %>
<div class="actions">
<%= link_to 'Créer un nouveau Lieu', new_village_path, :class => "btn btn-warning" %>
</div>
<table class="table table-responsive table-hover table-striped">
  <thead>
    <tr>
      <th>Commune</th>
      <th>Salle</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @villages.each do |village| %>
      <tr>
        <td><%= village.commune %></td>
        <td><%= village.salle %></td>
        <td><%= link_to 'Voir', village, :class => "btn btn-primary" %></td>
        <td><%= link_to 'Éditer', edit_village_path(village), :class => "btn btn-warning" %></td>
        <td><%= link_to 'Supprimer', village, method: :delete, data: { confirm: 'Are you sure?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<% end %>
<br>

app/views/villages/new.html.erb
<center>
<% if can? :manage, Village %>
  <h1>Créer un nouveau Lieu</h1>
	<div class="container">
		<%= render 'form' %>
		<%= link_to 'Retour à la liste des Villages', villages_path, :class => "btn btn-primary active" %>
	</div>
<% end %>
</center>
<br>

app/views/villages/show.html.erb
<center>
<h2>
  <strong>Commune:</strong>
  <%= @village.commune %>
</h2>

<h2>
  <strong>Salle:</strong>
  <%= @village.salle %>
</h2>
<%= link_to 'Editer', edit_village_path(@village), :class => "btn btn-warning" %> |
<%= link_to 'Retour liste des lieux', villages_path, :class => "btn btn-primary" %>
</center>