config/routes.rb
Rails.application.routes.draw do
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
	root to: "calendar#calendrier", :lieu => "tous les lieux"
	get 'log_in' => 'user_sessions#new', :as => :log_in
	post 'log_out' => 'user_sessions#destroy', :as => :log_out

  resources :reset_passwords, only: [:new, :create, :update, :edit]
	resource :calendar, only: [:calendrier, :aide], controller: :calendar
	resource :iframe, only: [:calendrier_iframe], controller: :iframe
	resource :specific_iframe, only: [:specific_calendrier_iframe], controller: :specific_iframe
	resources :ics
	resources :seances
	resources :villages
	resources :films
	resources :classifications
	resources :users
	resources :user_sessions, only: [:new, :create, :destroy]
	resources :disponibilites
	get 'specific_calendrier_iframe' => 'specific_iframe#specific_calendrier_iframe'
	get 'calendrier_iframe' => 'iframe#calendrier_iframe'
	get 'aide' => 'calendar#aide'
	get 'calendrier' => 'calendar#calendrier'
	get 'a_completer' => 'seances#a_completer'
	get 'mes_seances' => 'seances#mes_seances'
	get 'toutes_mes_seances' => 'seances#toutes_mes_seances'
	get 'seances_passees' => 'seances#seances_passees'
	get 'edition_calendrier' => 'seances#edition_calendrier'
	get 'entrees' => 'seances#entrees'
	get 'export_csv' => 'seances#export_csv'
	get 'export_nodon_csv' => 'seances#export_nodon_csv'
	get 'export_cc_csv' => 'seances#export_cc_csv'
	get 'export_tournee_csv' => 'seances#export_tournee_csv'
	get 'export_ics' => 'ics#export_ics'
	get 'export_cc_ics' => 'ics#export_cc_ics'
	get 'export_nodon_ics' => 'ics#export_nodon_ics'
	get 'export_tournee_ics' => 'ics#export_tournee_ics'
	get 'ecranvillage' => 'films#ecranvillage'
	get 'films_a_venir' => 'films#films_a_venir'
	get 'tous_les_films' => 'films#tous_les_films'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/film.rb
class Film < ApplicationRecord
	    has_many :seances, :dependent => :destroy, :inverse_of => :film
		  accepts_nested_attributes_for :seances, :allow_destroy => true
		  has_many :villages, :through => :seances
		  has_and_belongs_to_many :classifications
		  validates :id, :uniqueness => true
	    validates :titrefilm, :uniqueness => true
      validates :import_id, :uniqueness => true

	    def self.films_3_semaines
	        films_3_semaines = Film.where({ updated_at: (3.week.ago.midnight..(Date.today + 1))}).order(updated_at: :desc)
	    end

	    def self.films_2_mois_avant
	        films_2_mois_avant = Film.where({ updated_at: (2.month.ago.midnight..(Date.today + 1))})
	    end

	    def self.films_mois
	    	films_mois = Film.where({updated_at: 1.month.ago.midnight..(Date.today + 1)}).order(created_at: :asc)
	    end

	    def self.films_entrees
	        films_entrees = film.seances.where(horaire: date_range)
	    end

end

app/controllers/films_controller.rb
class FilmsController < ApplicationController

  skip_before_action :require_login, only: [:index, :films_a_venir, :ecranvillage, :show, :tous_les_films]
  before_action :set_film, only: [:show, :edit, :update, :destroy]

  require 'httparty'

  # GET /ecranvillage.json
  def ecranvillage
       @films = Film.all
       response = HTTParty.get('https://ecranvillage.net/wp-json/ecranvillage-api/v2/export/?nocache')
       puts response.body, response.code, response.message, response.headers.inspect
       JSON.parse(response.body).each do |item|
       nouveaux_films = Film.new( :import_id => item["id"], :titrefilm => item["titrefilm"], :description => item["description"], :affiche => item["affiche"] )
       nouveaux_films.save
    end
  end

  # GET /films
  # GET /films.json
  def index
    @films = Film.all
    @seances = Seance.all
    @search = Film.search(params[:q])
    @films = @search.result(distinct: true).page params[:page]
  end

  # GET /films
  # GET /films.json
  def films_a_venir
    @seances = Seance.all
    @films = Film.all
  end

# GET /films
# GET /films.json
  def tous_les_films
    @films = Film.all
  end

  # GET /films/1
  # GET /films/1.json
  def show
  end

  # GET /films/new
  def new
    @film = Film.new
  end

  # GET /films/1/edit
  def edit
  end

  # POST /films
  # POST /films.json
  def create
    @film = Film.new(film_params)

    respond_to do |format|
      if @film.save
        format.html { redirect_to @film, notice: 'Le Film a bien été créé.' }
        format.json { render :show, status: :created, location: @film }
      else
        format.html { render :new }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /films/1
  # PATCH/PUT /films/1.json
  def update
    respond_to do |format|
      if @film.update(film_params)
        format.html { redirect_to @film, notice: 'Le Film a bien été mis à jour.' }
        format.json { render :show, status: :ok, location: @film }
      else
        format.html { render :edit }
        format.json { render json: @film.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /films/1
  # DELETE /films/1.json
  def destroy
    @film.destroy
    respond_to do |format|
      format.html { redirect_to films_url, notice: 'Le Film a bien été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_film
      @film = Film.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def film_params
      params.require(:film).permit(:import_id, :titrefilm, :description, :distribution, :affiche, :updated_at, classification_ids:[])
    end
end

app/helpers/films_helper.rb
module FilmsHelper
end

app/views/films/ecranvillage.html.erb
<% response = HTTParty.get('https://ecranvillage.net/wp-json/ecranvillage-api/v2/export/?nocache') %>

       <% puts response.body %>
<div class="container">
    <center><h1>Importer les nouveaux Films</h1>
    <h1><strong>Bravo, en arrivant ici, vous venez d'ajouter les Films à venir du site d'Ecranvillage</strong></h1></p>
    <%= link_to 'Retour à la liste de films', films_a_venir_path, :class => "btn btn-lg btn-success" %>
    <h2>Liste des Films à venir sur le site d'Ecran Village</h2></center>
      <p><%= response.body.gsub!(/\\u([0-9a-z]{4})/) {|s| [$1.to_i(16)].pack("U")} %></p>
      <strong><%= response.message %> <%= response.code %></strong>
</div>
<br>

app/views/films/edit.html.erb
<center><h1>Editer un Film</h1>
<div class="container">
    <% if can? :manage, @film %>
    <div class="container">
	<%= render 'form' %>
	</div>
	<% end %>
	<%= link_to 'Voir', @film, :class => "btn btn-primary active" %>
	<%= link_to 'Retour à la liste des Films', films_a_venir_path, :class => "btn btn-success" %>
</div>
</center>
<br>

app/views/films/films_a_venir.html.erb
<div class="container">
    <div class="actions">
        <%= link_to 'Calendrier Général', root_path(:lieu => "tous les lieux"), :class => "btn btn-default btn-lg" %>
    </div>
</div>

    <div class="cine">
        <h1 class="cine-titre"><strong>Films du mois</strong></h1>
        <p class="cine-titre">( depuis le <%= l 3.week.ago %> )</p>
    </div>

<br>
<div class="container">
<% if can? :manage, @films %>
    <div class="btn-group">
    <button type="button" class="btn btn-danger">Ajouter</button>
        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Créer une nouvelle séance', new_seance_path, :class => "btn btn-primary active" %></li>
            <li><%= link_to 'Créer une nouveau lieu', new_village_path, :class => "btn btn-primary active" %></li>
            <li class="divider"></li>
            <li><%= link_to 'Ajouter les nouveaux films à venir', ecranvillage_path, :class => "btn btn-danger active" %></li>
        </ul>
    </div>
<% end %>
</div>
<br>

<div class="container">
<% if can? :update, Seance %>
    <div class="actions">
        <%= link_to 'Rechercher un film', films_path, :class => "btn btn-warning" %>
    </div>
<% end %>
</div>
<br>
<div class="film-seances">
    <% @films.order(updated_at: :asc).each do |film| %>
    <% seances = film.seances.seances_1_semaine_avant_2_mois_apres %>
    <% if seances.present? %>
        <div class="seance description">
            <div class="container">
                <center><h3 id="<%= film.titrefilm.upcase %>"><span class="glyphicon glyphicon-film"></span> <strong><%=raw film.titrefilm.upcase %></strong></h3></center>
            </div>
            <div class="container">
                <center>
                <% if can? :manage, @film %>
                    <%= link_to edit_film_path(film), class: "btn btn-warning", :title =>"Modifier" do %>
                        <i class="glyphicon glyphicon-pencil"></i>
                    <% end %>
                    <%= link_to film, method: :delete, data: { confirm: 'En êtes vous sûr ?'}, :class => "btn btn-danger", :title =>"Supprimer" do %>
                        <i class="glyphicon glyphicon-trash"></i>
                    <% end %>
                    <% if film.distribution.present? %>
                        <%= film.distribution %>,
                    <% end %>
                <% end %>
                <% if film.classifications.present? %>
                    <%= film.classifications.map(&:nom_classification).sort.join(", ") %>
                <% end %>
                </center>
            </div>
        <div class="description">
            <% if film.affiche.present? %>
                <div class="row">
                    <div class=".col-xs-6 .col-md-4">
                        <img class="affiche" style="float:left" src="<%= film.affiche %>" />
                        <div class="apropos">
                            <div class="content-heading text-center"><h3>A propos :</h3>
                            </div>
                            <div class="text-center italic">
                                <p><%=simple_format h film.description %> <%= link_to 'en savoir plus', "https://ecranvillage.net/?p=#{film.import_id}", :title => "article sur le site d'Ecran Village", :target => "_blank", :rel => "noopener noreferrer" %></p>
                            </div>
                        </div>
                    </div>
                    <div style="clear:both"></div>
                </div>
            <% else %>
                <h3>A propos :</h3>
                    <div class="text-center italic">
                        <p><%=simple_format h film.description %></p>
                    </div>
            <% end %>
        </div>
        <h4><strong>Séances à venir :</strong></h4>
        <% futures_seances = film.seances.seances_asc.each.map do |seance| if Date.today < seance.horaire %>
          <%=  content_tag :film_id, futures_seances do %>
            <% if seance.annulee != "Annulée" %>
                         <p><span class="glyphicon glyphicon-time"></span> <%= l seance.horaire, format: :very_long %></p>
                         <p><span class="glyphicon glyphicon-home"></span> <%= seance.village.commune.upcase %> <em>(<%= seance.village.salle %>)</em>
                        <% if seance.version.present? %>
                        , <span class="glyphicon glyphicon-info-sign"></span> <%= seance.version %>
                        <% end %>
                        <% if seance.audio_description.present? %>
                        , <i class="fa fa-audio-description"></i> <%= seance.audio_description %> <i class="fa fa-low-vision"></i>
                        <% end %>
                        </p>
                        <% if seance.extras.present? %>
                        <p><span class="glyphicon glyphicon-info-sign"></span> <%= seance.extras %></p>
                        <% end %>
                    <% if can? :update, Seance %>
                        <p><span class="glyphicon glyphicon-facetime-video"></span> <strong><%= seance.projection %></strong> - <span class="glyphicon glyphicon-briefcase"></span> <strong><%= seance.caisse %></strong></p>
                        <%= link_to edit_seance_path(seance), class: "btn btn-warning", :title =>"Modifier" do %>
                        <i class="glyphicon glyphicon-pencil"></i>
                        <% end %>
                    <% if can? :manage, @seance %>
                         <%= link_to seance, method: :delete, data: { confirm: 'En êtes vous sûr ?'}, :class => "btn btn-danger", :title =>"Supprimer" do %>
                        <i class="glyphicon glyphicon-trash"></i>
                        <% end %>
                      <% end %>
                    <% end %>
                    <br>
            <% else %>
                <p><strong><span class="glyphicon glyphicon-warning-sign"></span> <%= seance.annulee %></strong></p>
                <div class="annule">
                        <p><span class="glyphicon glyphicon-time"></span> <%= l seance.horaire, format: :very_long %>
                        <p><span class="glyphicon glyphicon-home"></span> <%= seance.village.commune.upcase %> <em>(<%= seance.village.salle %>)</em></p>
                        <% if seance.version.present? %>
                        <p><span class="glyphicon glyphicon-info-sign"></span> <%= seance.version %>
                        <% end %>
                        <% if seance.audio_description.present? %>
                          <p><i class="fa fa-audio-description"></i> <%= seance.audio_description %> <i class="fa fa-low-vision"></i></p>
                        <% end %>
                        </p>
                        <% if seance.extras? %>
                        <p><span class="glyphicon glyphicon-info-sign"></span> <%= seance.extras %></p>
                        <% end %>
                    <% if can? :manage, seance %>
                        <%= link_to edit_seance_path(seance), class: "btn btn-warning", :title =>"Modifier" do %>
                        <i class="glyphicon glyphicon-pencil"></i>
                        <% end %>
                        <%= link_to seance, method: :delete, data: { confirm: 'En êtes vous sûr ?'}, :class => "btn btn-danger", :title =>"Supprimer" do %>
                        <i class="glyphicon glyphicon-trash"></i>
                        <% end %>
                    <% end %>
                </div>
                <br>
              <% end %>
            <% end %>
        <% end %>
    <% end %>
        <h4><strong>Séances passées :</strong></h4>
        <% seances_passees = film.seances.seances_passees_3_semaines.seances_desc.each.map do |seance| if Date.today > seance.horaire %>
           <%= content_tag :film_id, seances_passees do %>
            <% if seance.annulee != "Annulée" %>
                <p><span class="glyphicon glyphicon-time"></span> <%= l seance.horaire, format: :very_long %></p>
                <p><span class="glyphicon glyphicon-home"></span> <%= seance.village.commune.upcase %> <em>(<%= seance.village.salle %>)</em>
            <% if seance.version.present? %>
                , <span class="glyphicon glyphicon-info-sign"></span> <%= seance.version %>
            <% end %>
            <% if seance.audio_description.present? %>
               , <i class="fa fa-audio-description"></i> <%= seance.audio_description %> <i class="fa fa-low-vision"></i>
            <% end %>
                </p>
            <% if seance.extras.present? %>
                <p><span class="glyphicon glyphicon-info-sign"></span> <%= seance.extras %></p>
            <% end %>
              <% if can? :update, Seance %>
                        <p><span class="glyphicon glyphicon-facetime-video"></span> <strong><%= seance.projection %></strong> - <span class="glyphicon glyphicon-briefcase"></span> <strong><%= seance.caisse %></strong></p>
                        <%= link_to edit_seance_path(seance), class: "btn btn-warning", :title =>"Modifier" do %>
                        <i class="glyphicon glyphicon-pencil"></i>
                        <% end %>
                    <% if can? :manage, @seance %>
                         <%= link_to seance, method: :delete, data: { confirm: 'En êtes vous sûr ?'}, :class => "btn btn-danger", :title =>"Supprimer" do %>
                        <i class="glyphicon glyphicon-trash"></i>
                        <% end %>
                      <% end %>
                    <% end %>
                </p>
                <br>
            <% else %>
                <p><span class="glyphicon glyphicon-warning-sign"></span> <%= seance.annulee %></p>
                <div class="annule">
                    <p><span class="glyphicon glyphicon-time"></span> <%= l seance.horaire, format: :very_long %></p>
                    <p><span class="glyphicon glyphicon-home"></span> <%= seance.village.commune.upcase %> (<%= seance.village.salle %>)</p>
                    <% if seance.version.present? %>
                    <p><span class="glyphicon glyphicon-info-sign"></span> <%= seance.version %></p>
                    <% end %>
                    <% if seance.audio_description.present? %>
                    <p><i class="fa fa-audio-description"></i> <%= seance.audio_description %> <i class="fa fa-low-vision"></i></p>
                    <% end %>
                    <% if seance.extras.present? %>
                    <p><span class="glyphicon glyphicon-info-sign"></span> <%= seance.extras %></p>
                    <% end %>
                <% if can? :manage, Seance %>
                    <p><span class="glyphicon glyphicon-pencil"></span> <%= link_to 'Modifier la séance', edit_seance_path(seance), :class => "btn btn-warning" %></p>
                     <p><span class="glyphicon glyphicon-trash"></span> <%= link_to 'Supprimer la séance', seance, method: :delete, data: { confirm: 'En êtes vous sûr ?'}, :class => "btn btn-danger" %></p>
                <% end %>
               </div>
            <br>
            <%end%>
          <% end %>
         <% end %>
        <%end %>
        </div>
        <center><span class="glyphicon glyphicon-facetime-video"></span> <span class="glyphicon glyphicon-film"></span> <span class="glyphicon glyphicon-facetime-video"></span> <span class="glyphicon glyphicon-film"></span> <span class="glyphicon glyphicon-facetime-video"></span> <span class="glyphicon glyphicon-film"></span> <span class="glyphicon glyphicon-facetime-video"></span> <span class="glyphicon glyphicon-film"></span> <span class="glyphicon glyphicon-facetime-video"></span></center>
       <% end %>
      <% end %>
    </div>
</div>
</br>
<%= link_to '', films_a_venir_path, :class => "back-to-top", :title => 'Retour haut de page' %>

app/views/films/index.html.erb
<center><h1><strong>Films</strong></h1></center>
<div class="container">
    <div class="actions">
        <%= link_to 'Retour à la page Films à venir', films_a_venir_path, :class => "btn btn-primary btn-block"  %>
    </div>
</div>
<br>
<% if can? :manage, @films %>
  <div class="container">
    <div class="btn-group">
          <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
          Ajouter <span class="caret"></span>
          </button>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Créer une nouvelle seance', new_seance_path, :class => "btn btn-warning btn-block" %></li>
            <li><%= link_to 'Créer une nouveau lieu', new_village_path, :class => "btn btn-warning btn-block" %></li>
            <li class="divider"></li>
            <li><%= link_to 'Ajouter les nouveaux films à venir', ecranvillage_path, :class => "btn btn-block btn-danger" %></li>
           </ul>
        </div>
  </div>
<% end %>
<div class="container">
<center>
<fieldset class="search-field">
   <legend>Recherche par titre et/ou classification</legend>
    <%= search_form_for @search do |f| %>
    <div class="field">
      <%= f.label :titrefilm_cont, "Film(s) contien(nen)t" %>
      <%= f.text_field :titrefilm_cont %>
    </div>

    <div class="field">
     <%= f.label "Zone de classifications" %><br />
      <%= f.collection_check_boxes :classifications_id_in_any, Classification.all, :id, :nom_classification do |b| %>
        <div class="collection-check-box">
          <%= b.check_box %>
          <%= b.label %>
        </div>
      <% end %>
    </div>
    <div class="actions">
        <%= f.submit "Rechercher" %>
    </div>
    <% end %>
</fieldset>
</center>
</div>
<br>
<div class="container">

    <h3>Il y a pour cette recherche : <strong><%= @search.result.length %></strong> film(s)</strong>: </h3>
    <%= paginate @films %>

    <% @films.order(updated_at: :desc).each do |film| %>
     <% film_seances_semaine = film.seances.where(annulee: [nil, ""]) %>
      <% film_vernoux= film_seances_semaine.where(village_id: 4) %>
      <% film_lamastre = film_seances_semaine.where(village_id: 8) %>
      <% film_chalencon = film_seances_semaine.where(village_id: 5) %>

<div class="row">
  <table class="table table-responsive table-hover table-striped table-croped">
    <center><h3><span class="glyphicon glyphicon-film"></span> <strong><%= film.titrefilm.upcase %></strong>
    <% if can? :manage, @films %></h3>
      <div class="btn-group">
        <button type="button"
        class="btn btn-primary btn-xs dropdown-toggle" data-toggle="dropdown">
        Actions <span class="caret"></span>
        </button>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to 'Modifier', edit_film_path(film), class: "btn btn-warning active" %></li>
          <li><%= link_to 'Supprimer', film, method: :delete, data: { confirm: 'En êtes vous sûr ?'}, :class => "btn btn-danger active" %></li>
         </ul>
      </div>
    </center>
    <% end %>
    <br>
    <% if film.classifications.present? %>
    <center>classé <%= film.classifications.map(&:nom_classification) %></center>
    <% end %>
    <% if film.distribution.present? %>
    <center>distribué par <%= film.distribution %></center>
    <% end %>
    <thead>
      <th>
         <tr>
           <th>Lieu</th>
           <th>Nombre de séances</th>
           <th>Billets scolaires</th>
           <th>Billets enfants</th>
           <th>Billets adultes</th>
           <th>Total Billets</th>
         </tr>
       </th>
    </thead>
    <tbody>
      <tr>
        <td class="active">Tous</td>
        <td class="warning"><strong><%= film_seances_semaine.length %></strong> séance(s)</td>
        <td class="info"><strong><%= film_seances_semaine.sum("billets_scolaires") %></strong> scolaire(s) scolaire(s)</td>
        <td class="info"><strong><%= film_seances_semaine.sum("billets_enfants") %></strong> enfant(s) enfant(s)</td>
        <td class="info"><strong><%= film_seances_semaine.sum("billets_adultes") %></strong> adulte(s)</td>
        <td class="warning"><strong><%= film_seances_semaine.sum("total_billets") %></strong> en total</td>
      </tr>
      <tr>
        <td class="active">Vernoux</td>
        <td class="warning"><strong><%= film_vernoux.length %></strong> séance(s)</td>
        <td class="info"><strong><%= film_vernoux.sum("billets_scolaires") %></strong> scolaire(s)</td>
        <td class="info"><strong><%= film_vernoux.sum("billets_enfants") %></strong> enfant(s)</td>
        <td class="info"><strong><%= film_vernoux.sum("billets_adultes") %></strong> adulte(s)</td>
        <td class="warning"><strong><%= film_vernoux.sum("total_billets") %></strong> en total</td>
      </tr>
      <tr>
        <td class="active">Lamastre</td>
        <td class="warning"><strong><%= film_lamastre.length %></strong> séance(s)</td>
        <td class="info"><strong><%= film_lamastre.sum("billets_scolaires") %></strong> scolaire(s)</td>
        <td class="info"><strong><%= film_lamastre.sum("billets_enfants") %></strong> enfant(s)</td>
        <td class="info"><strong><%= film_lamastre.sum("billets_adultes") %></strong> adulte(s)</td>
        <td class="warning"><strong><%= film_lamastre.sum("total_billets") %></strong> en total</td>
      </tr>
      <tr>
        <td class="active">Chalencon</td>
        <td class="warning"><strong><%= film_chalencon.length %></strong> séance(s)</td>
        <td class="info"><strong><%= film_chalencon.sum("billets_scolaires") %></strong> scolaire(s)</td>
        <td class="info"><strong><%= film_chalencon.sum("billets_enfants") %></strong> enfant(s)</td>
        <td class="info"><strong><%= film_chalencon.sum("billets_adultes") %></strong> adulte(s)</td>
        <td class="warning"><strong><%= film_chalencon.sum("total_billets") %></strong> en total</td>
      </tr>
      <tr>
        <td class="active">Itinérance</td>
        <td class="warning"><strong><%= film_seances_semaine.length  - (film_vernoux.length  + film_lamastre.length  + film_chalencon.length) %></strong></td>
        <td class="info"><strong><%= film_seances_semaine.sum("billets_scolaires") - (film_vernoux.sum("billets_scolaires") + film_lamastre.sum("billets_scolaires") + film_chalencon.sum("billets_scolaires")) %></strong></td>
        <td class="info"><strong><%= film_seances_semaine.sum("billets_enfants") - (film_vernoux.sum("billets_enfants")  + film_lamastre.sum("billets_enfants") + film_chalencon.sum("billets_enfants")) %></strong></td>
        <td class="info"><strong><%= film_seances_semaine.sum("billets_adultes") - (film_vernoux.sum("billets_adultes") + film_lamastre.sum("billets_adultes") + film_chalencon.sum("billets_adultes")) %></strong></td>
        <td class="warning"><strong><%= film_seances_semaine.sum("total_billets") - (film_vernoux.sum("total_billets") + film_lamastre.sum("total_billets") + film_chalencon.sum("total_billets")) %></strong></td>
      </tr>
      <tr>
        <td class="active">Tournée (Lamastre, Chalencon, Itinérance)</td>
        <td class="warning"><strong><%= film_seances_semaine.length - film_vernoux.length %></strong> séance(s)</td>
        <td class="info"><strong><%= film_seances_semaine.sum("billets_scolaires") - film_vernoux.sum("billets_scolaires") %></strong> scolaire(s)</td>
        <td class="info"><strong><%= film_seances_semaine.sum("billets_enfants") - film_vernoux.sum("billets_enfants") %></strong> enfant(s)</td>
        <td class="info"><strong><%= film_seances_semaine.sum("billets_adultes") - film_vernoux.sum("billets_adultes") %></strong> adulte(s)</td>
        <td class="warning"><strong><%= film_seances_semaine.sum("total_billets") - film_vernoux.sum("total_billets") %></strong> en total</td>
      </tr>
    </tbody>
  <% end %>
  </table>
 </div>
</div>

app/views/films/new.html.erb
<center>
<h1>Nouveau Film</h1>

<%= render 'form', film: @film %>

<%= link_to 'Retour liste des films', films_path, :class => "btn btn-primary" %>
</center>

app/views/films/show.html.erb
<center>
<div class="container">
	<div class="description">
	  <strong>Film:</strong>
	  <%= raw @film.titrefilm %>
	  <%=simple_format h @film.description %>
	  <% if @film.classifications.present? %>
	    <%= @film.classifications.map(&:nom_classification).sort.join(", ") %>
	  <% end %>
	</div>
<br>
</center>
	<div class="btn-group">
    <button type="button" class="btn btn-danger">Actions</button>
        <button type="button" class="btn btn-danger dropdown-toggle" data-toggle="dropdown">
        <span class="caret"></span>
        <span class="sr-only">Toggle Dropdown</span>
        </button>
        <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'Modifier', edit_film_path(@film), :class => "btn btn-warning active" %></li>
            <li><%= link_to 'Créer une nouvelle seance', new_seance_path, :class => "btn btn-primary active" %></li>
            <li class="divider"></li>
            <li><%= link_to 'Retour à la liste des Films', films_a_venir_path, :class => "btn btn-success active" %></li>
        </ul>
    </div>
</div>
<br>