config/routes.rb
Rails.application.routes.draw do
	mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
	mount RailsAdminImport::Engine => '/rails_admin_import', :as => 'rails_admin_import'
	root to: "calendar#calendrier", :lieu => "tous les lieux"
	get 'log_in' => 'user_sessions#new', :as => :log_in
	post 'log_out' => 'user_sessions#destroy', :as => :log_out

  resources :reset_passwords, only: [:new, :create, :update, :edit]
	resource :calendar, only: [:calendrier, :aide], controller: :calendar
	resource :iframe, only: [:calendrier_iframe], controller: :iframe
	resource :specific_iframe, only: [:specific_calendrier_iframe], controller: :specific_iframe
	resources :ics
	resources :seances
	resources :villages
	resources :films
	resources :classifications
	resources :users
	resources :user_sessions, only: [:new, :create, :destroy]
	resources :disponibilites
	get 'specific_calendrier_iframe' => 'specific_iframe#specific_calendrier_iframe'
	get 'calendrier_iframe' => 'iframe#calendrier_iframe'
	get 'aide' => 'calendar#aide'
	get 'calendrier' => 'calendar#calendrier'
	get 'a_completer' => 'seances#a_completer'
	get 'mes_seances' => 'seances#mes_seances'
	get 'toutes_mes_seances' => 'seances#toutes_mes_seances'
	get 'seances_passees' => 'seances#seances_passees'
	get 'edition_calendrier' => 'seances#edition_calendrier'
	get 'entrees' => 'seances#entrees'
	get 'export_csv' => 'seances#export_csv'
	get 'export_nodon_csv' => 'seances#export_nodon_csv'
	get 'export_cc_csv' => 'seances#export_cc_csv'
	get 'export_tournee_csv' => 'seances#export_tournee_csv'
	get 'export_ics' => 'ics#export_ics'
	get 'export_cc_ics' => 'ics#export_cc_ics'
	get 'export_nodon_ics' => 'ics#export_nodon_ics'
	get 'export_tournee_ics' => 'ics#export_tournee_ics'
	get 'ecranvillage' => 'films#ecranvillage'
	get 'films_a_venir' => 'films#films_a_venir'
	get 'tous_les_films' => 'films#tous_les_films'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/classification.rb
class Classification < ApplicationRecord
	has_and_belongs_to_many :films
	has_many :seances, :through => :films
end

app/controllers/classifications_controller.rb
class ClassificationsController < ApplicationController

  before_action :set_classification, only: [:show, :edit, :update, :destroy]

  # GET /classifications
  # GET /classifications.json
  def index
    @classifications = Classification.all
    @films = Film.all
    @seances = Seance.all
  end

  # GET /classifications/1
  # GET /classifications/1.json
  def show
  end

  # GET /classifications/new
  def new
    @classification = Classification.new
  end

  # GET /classifications/1/edit
  def edit
  end

  # POST /classifications
  # POST /classifications.json
  def create
    @classification = Classification.new(classification_params)

    respond_to do |format|
      if @classification.save
        format.html { redirect_to @classification, notice: 'la classification a bien été créée.' }
        format.json { render :show, status: :created, location: @classification }
      else
        format.html { render :new }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /classifications/1
  # PATCH/PUT /classifications/1.json
  def update
    respond_to do |format|
      if @classification.update(classification_params)
        format.html { redirect_to @classification, notice: 'la classification a bien été mise à jour.' }
        format.json { render :show, status: :ok, location: @classification }
      else
        format.html { render :edit }
        format.json { render json: @classification.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /classifications/1
  # DELETE /classifications/1.json
  def destroy
    @classification.destroy
    respond_to do |format|
      format.html { redirect_to classifications_url, notice: 'la classification a été supprimée.' }
      format.json { head :no_content }
    end
  end

  private
  
    # Use callbacks to share common setup or constraints between actions.
    def set_classification
      @classification = Classification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def classification_params
      params.require(:classification).permit(:nom_classification, :film_id)
    end
end

app/helpers/classifications_helper.rb
module ClassificationsHelper
end

app/views/classifications/_form.html.erb
<%= form_for(@classification) do |f| %>
  <% if @classification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(classification.errors.count, "error") %> prohibited this classification from being saved:</h2>

      <ul>
      <% classification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nom_classification %>
    <%= f.text_field :nom_classification %>
  </div>

  <div class="actions">
     <input type="submit" class="btn btn-lg btn-warning" value="Valider" />
  </div>
<% end %>

app/views/classifications/edit.html.erb
<h1>Editer une Classification</h1>

<%= render 'form' %>

<%= link_to 'Voir', @classification, :class => "btn btn-success" %> |
<%= link_to 'Retour à la liste', classifications_path, :class => "btn btn-primary" %>

app/views/classifications/index.html.erb
<center><h1>Liste Classifications</h1></center>
<div class="container">
  <%= link_to 'Créer une Nouvelle Classification', new_classification_path, :class => "btn btn-warning" %>
</div>
<br>
<table class="table table-responsive table-hover table-striped">
  <thead>
    <tr>
      <th>Nom</th>
      <th>Nombre de Films</th>
      <th>Nombre de séances</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @classifications.each do |classification| %>
      <tr>
        <td><%= classification.nom_classification %></td>
        <td><%= classification.films.length %></td>
        <td><%= classification.seances.length %>
        <td><%= link_to 'Voir', classification, :class => "btn btn-primary" %></td>
        <td><%= link_to 'Éditer', edit_classification_path(classification), :class => "btn btn-warning" %></td>
        <td><%= link_to 'Supprimer', classification, method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, :class => "btn btn-danger"  %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<br>
<h1>Liste des Films Classés</h1>
<table class="table table-responsive table-hover table-striped">
  <thead>
    <tr>
      <th>Films</th>
      <th>Nom (classification)</th>
      <th>Nombres de séances</th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @classifications.each do |classification| %>
    <% classification.films.each do |classification_film| %>
      <tr>
        <td><%= classification_film.titrefilm %></td>
        <td><%= classification.nom_classification %></td>
        <td><%= classification_film.seances.length %></td>
        <td><%= link_to 'Voir', classification, :class => "btn btn-primary" %></td>
        <td><%= link_to 'Éditer', edit_classification_path(classification), :class => "btn btn-warning" %></td>
        <td><%= link_to 'Supprimer', classification, method: :delete, data: { confirm: 'Êtes-vous sûr ?' }, :class => "btn btn-danger" %></td>
      </tr>
    <% end %>
    <% end %>
  </tbody>
</table>
<%= link_to '', classifications_path, :class => "back-to-top", :title => 'Retour haut de page' %>
<br>

app/views/classifications/new.html.erb
<h1>Nouvelle Classification</h1>

<%= render 'form', classification: @classification %>

<%= link_to 'Retour', classifications_path, :class => "btn btn-primary" %>

app/views/classifications/show.html.erb
<center>
<h2>
  <strong>Nom de la classification:</strong>
  <%= @classification.nom_classification %>
</h2>

<%= link_to 'Editer', edit_classification_path(@classification), :class => "btn btn-warning" %> |
<%= link_to 'Retour à la liste', classifications_path, :class => "btn btn-primary" %>
</center>